name: C++ Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: |
        msbuild ConsoleApplication1.vcxproj /p:Configuration=Release /p:Platform=x64
      
        dir /s /b /a:-D *.exe
